# bi门户配置
bi:
  error-log:
    enable: false
  error-code:
    enable: false
  access-log:
    enable: false
  swagger:
    title: insight微服务
    description: 提供insight的所有功能
    version: 3.0.1
  # 多租配置
  tenant:
    # db多租配置显式关闭
    enable-db: false
    # Job多租配置显式关闭
    enable-job: false
    # redis多租配置显式关闭
    enable-redis: false
    # rabbit MQ多租配置显式关闭
    enable-rabbit: false
    # rocket MQ多租配置显式关闭
    enable-rocket: false