# swagger config
springdoc:
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui.html
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

knife4j:
  enable: true # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn

# mybatis plus 双数据源
spring:
  data:
    redis:
      password: C9J&83^8H&AefF
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1ms
      timeout: 10000ms
      cluster:
        nodes: 10.54.167.21:7000,10.54.167.21:7001,10.54.167.136:7000,10.54.167.136:7001,10.54.167.113:7000,10.54.167.113:7001
  datasource:
    dynamic:
      enabled: false
    primary:
      url: jdbc:mysql://10.54.167.227:3306/futech_bi?useSSL=false&autoReconnect=true&characterEncoding=utf8
      username: test_rw
      password: test2FGHHGF#$$a250ee20883c23e
      driver-class-name: com.mysql.cj.jdbc.Driver
    second:
      url: jdbc:bytehouse://gateway.aws-ap-southeast-1.bytehouse.cloud:19000/ddl_test?secure=true
      username: bytehouse
      password: QCDyIaYnEl:tXzEP40sjL
      driver-class-name: com.bytedance.bytehouse.jdbc.ByteHouseDriver
      poolName: BI-Pool
    ### 修改配置开始-新增 ###
    third:
      url: jdbc:postgresql://10.48.32.189:5432/superset_db?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true
      username: user_superset
      password: GGHNg9BkAgfGWq
      driver-class-name: org.postgresql.Driver
    ### 修改配置结束 ###
    useTimeZone: Asia/Shanghai
    idleTimeout: 180000
    maxPoolSize: 20
    maxLifetime: 1800000
    connectionTimeout: 1800000
    socketTimeout: 1800000
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    filter:
      stat:
        enabled: true
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# anomaly 智能分析树图index结构映射
anomaly:
  indexes:
    index_map:
      ggr_today:
        queryField: ggr_today
        resultField: GGR
      ggr_decline_rate:
        queryField: ggr_today
        resultField: 下钻GGR
      betamt_decline_rate:
        queryField: betamt_today
        resultField: 投注金额
      btloss_decline_rate:
        queryField: btloss_today
        resultField: 投注负率
      betcnt_decline_rate:
        queryField: betcnt_today
        resultField: 投注次数
      btamavg_decline_rate:
        queryField: btamavg_today
        resultField: 投注次均额
      arpu_decline_rate:
        queryField: arpu_today
        resultField: ARPU
      dau_decline_rate:
        queryField: dau_today
        resultField: DAU
      promotion_all_cnt_incrate:
        queryField: promotion_all_cnt
        resultField: 优惠券发放次数
      APPLETZCS_cnt_incrate:
        queryField: APPLETZCS_cnt
        resultField: APPLETZCS优惠券发放
      promotion_all_cnt_incrate_2d:
        queryField: promotion_all_cnt
        resultField: 上日优惠券发放次数
      APPLETZCS_cnt_incrate_2d:
        queryField: APPLETZCS_cnt
        resultField: 上日APPLETZCS优惠券发放
      highamt_ratio_decline_rate:
        queryField: highamt_ratio_today
        resultField: 高额客群占比
      highcnt_ratio_decline_rate:
        queryField: highcnt_ratio_today
        resultField: 高频客群占比
      retention_7d_decline_rate:
        queryField: retention_7d_today
        resultField: 7日留存率
      New_ratio_decline_rate:
        queryField: New_ratio_today
        resultField: 新客群占比
      Growing_ratio_decline_rate:
        queryField: Growing_ratio_today
        resultField: 增长客群占比
      Stable_ratio_decline_rate:
        queryField: Stable_ratio_today
        resultField: 稳定客群占比
bi:
  tenant: # 多租户相关配置项
    enable: true
    ignore-urls:
      - /admin-api/insight/health # 健康检查, 和租户无关

risk:
  conditions:
    primary_risk_types:
      - num: 1
        display: 'frequent cross-city login'
        value: 'frequent cross-city login'
        desc: 'primary类型1'
      - num: 2
        display: 'login unusual city'
        value: 'login unusual city'
        desc: 'primary类型2'
    secondary_risk_types:
      - num: 1
        display: 'abnormal ip'
        value: 'abnormal ip'
        desc: 'secondary类型1'
      - num: 2
        display: 'abnormal behavior'
        value: 'abnormal behavior'
        desc: 'secondary类型2'
      - num: 3
        display: 'abormal device'
        value: 'abormal device'
        desc: 'secondary类型3'
    time_ranges:
      - num: 1
        display: 'Daily'
        value: 'daily'
        desc: '按天维度'
      - num: 2
        display: 'Monthly'
        value: 'monthly'
        desc: '按月维度'      
