# bi门户配置
bi:
  error-code:
    enable: false
  access-log:
    enable: false

spring:
  datasource:
    dynamic:
      enabled: false
    url: jdbc:mysql://10.30.46.2:3306/data_management_pf?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 1234qwer
    driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
  mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl